### ISSUE TITLE
panic: internal error on xcaddy build

### ISSUE THREAD

**Issue by Br33ce** [dulli/caddy-wol#1]
I tried with different plugins and only with this do I get:

`panic: internal error: can't find reason for requirement on github.com/google/pp                   rof@v0.0.0-20210407192527-94a9f03dee38

goroutine 1 [running]:
cmd/go/internal/modget.(*resolver).updateBuildList.func1({{0x276a210, 0x17}, {0x                   1822570, 0x22}})
        /usr/local/go/src/cmd/go/internal/modget/get.go:1760 +0x10c
cmd/go/internal/modget.(*resolver).updateBuildList(0x1bda280, {0x71f020, 0x181c0                   98}, {0x0, 0x0, 0x0})
        /usr/local/go/src/cmd/go/internal/modget/get.go:1765 +0x498
cmd/go/internal/modget.(*resolver).applyUpgrades(0x1bda280, {0x71f020, 0x181c098                   }, {0x0, 0x0, 0x0})
        /usr/local/go/src/cmd/go/internal/modget/get.go:1312 +0x2fc
cmd/go/internal/modget.runGet({0x71f020, 0x181c098}, 0xa090c8, {0x1818080, 0x2,                    0x2})
        /usr/local/go/src/cmd/go/internal/modget/get.go:351 +0x444
main.invoke(0xa090c8, {0x1818068, 0x5, 0x5})
        /usr/local/go/src/cmd/go/main.go:225 +0x400
main.main()
        /usr/local/go/src/cmd/go/main.go:179 +0x974
2023/02/09 10:30:54 [FATAL] exit status 2`

I tried on Go 1.20, 19.5, 19, and 18.1 nothing changed, so its maybe this plugin?

**Comment by francislavoie** [comment]
Discussion, for reference: https://caddy.community/t/xaddy-on-raspberry-b-build-with-plugin-wol/18821/13

There's a bug in `go get` that's causing a panic on certain dependencies. It's frustrating. I _think_ a workaround is to have plugins bump their minimum Caddy version to v2.6.3 to have their dependencies in sync.

**Comment by francislavoie** [comment]
Also FYI @dulli, please consider registering your plugin on https://caddyserver.com/download by making an account on the website and claiming your module ID. That way, your plugin will have more visibility and users will be able to find it easily :blush:

**Comment by francislavoie** [comment]
Yep, confirmed that fixes it, running `xcaddy build v2.6.3 --with github.com/dulli/caddy-wol@main` works now. Thanks!

(The `@main` shouldn't be necessary, Go is caching the latest commit locally so I had to tell it a specific branch to force it to try the latest commit, since it _just_ got merged)

**Comment by dulli** [comment]
Perfect, thanks for the quick pull request!

And also thank you for the heads-up about the plugin registry, I was wondering how to enter the module there but didn't find anything in the docs and then didn't have the time to further investigate back when I created this. No idea why I just didn't try to create an account though 😄

**Comment by Br33ce** [comment]
Thank you for the quick fix 😊 looking forward to seeing the plug in on the caddy website.
